#!/usr/bin/env python3
"""Exercise actual input, consequences, replay, and responsive rendering."""
from pathlib import Path
import json
import os
import sys
from playwright.sync_api import sync_playwright
ROOT = Path(__file__).resolve().parents[2]
def launch(playwright):
    # PW_CHROMIUM supports a separately installed browser on ARM hosts.
    executable = os.environ.get('PW_CHROMIUM')
    if not executable:
        candidates = sorted((Path.home()/'.cache/ms-playwright').glob('chromium-*/chrome-linux/chrome'))
        executable = str(candidates[-1]) if candidates else None
    options = {'headless': True}
    if executable:
        options['executable_path'] = executable
    return playwright.chromium.launch(**options), 'chromium'
HERE = Path(__file__).resolve().parent
ENTRY = sys.argv[1] if len(sys.argv)>1 else (HERE/'index.html').as_uri()
OUT=HERE/'evidence'; OUT.mkdir(exist_ok=True)
checks,errors=[],[]
def check(name, condition):
    assert condition, name
    checks.append(name)
with sync_playwright() as p:
    browser,engine=launch(p)
    context=browser.new_context(viewport={'width':1440,'height':1050},reduced_motion='reduce')
    page=context.new_page();page.on('pageerror',lambda e:errors.append(str(e)))
    page.goto(ENTRY)
    page.wait_for_function('window.journey && window.comparisonProbe && document.querySelector("#game canvas")')
    page.locator('#card-tracking').click()
    def snap(name):page.screenshot(path=str(OUT/(name+'.png')),full_page=True)
    def point(x,y,side=1):
        page.locator('#game').scroll_into_view_if_needed()
        box=page.locator('#game canvas').bounding_box()
        narrow=page.evaluate('matchMedia("(max-width:760px)").matches')
        width=480 if narrow else 960
        left=48 if narrow or side==0 else 536
        size=384 if narrow else 376
        page.mouse.click(box['x']+(left+(x+.5)/128*size)/width*box['width'],box['y']+(84+(y+.5)/128*size)/520*box['height'])
    def follow(outcome):
        page.locator('#follow').click()
        page.wait_for_function('comparisonProbe.state.phase==="result"')
        check('computed outcome '+outcome,page.evaluate('comparisonProbe.state.result.outcome')==outcome)
    check('entry gives goal and requires a target',page.locator('#follow').is_disabled() and 'движущийся' in page.locator('#tracking-episode h1').inner_text())
    check('third frame not exposed on entry',page.evaluate('comparisonProbe.state.result===null && comparisonProbe.game.scene.scenes[0].rects.length===2'))
    snap('entry')
    point(100,100)
    check('empty sky explains failed selection',page.locator('#follow').is_disabled() and 'не видит' in page.locator('#feedback').inner_text())
    point(58,68,side=0)
    check('first frame cannot choose target',page.locator('#follow').is_disabled())
    point(71,10)
    check('pointer selects measured source',page.evaluate('comparisonProbe.state.selection.point.x')==71)
    snap('selected')
    follow('stationary');snap('stationary')
    check('stationary has explanation and no reward',page.evaluate('comparisonProbe.state.journal.length')==0 and 'осталась' in page.locator('#outcome-title').inner_text())
    saved=page.evaluate('JSON.stringify(comparisonProbe.state.attempts[0])')
    page.locator('#retry').click();point(58,68);follow('moving');snap('moving')
    check('success possible without slider',page.evaluate('comparisonProbe.state.amount===0 && comparisonProbe.state.journal.length===1'))
    check('earlier attempt retained unchanged',saved==page.evaluate('JSON.stringify(comparisonProbe.state.attempts[0])'))
    check('retry recorded as already seen frame',page.evaluate('comparisonProbe.state.attempts[0].firstLook && !comparisonProbe.state.attempts[1].firstLook'))
    check('submitted result deeply frozen',page.evaluate('Object.isFrozen(comparisonProbe.state.attempts[1]) && Object.isFrozen(comparisonProbe.state.attempts[1].selection.point)'))
    check('observed position differs from prediction',page.evaluate('comparisonProbe.state.result.distancePx>0 && comparisonProbe.state.result.positions[2].x===91'))
    page.locator('#next-field').click()
    check('next field retains earned journal',page.evaluate('comparisonProbe.state.field===1 && comparisonProbe.state.journal.length===1'))
    page.locator('#tools summary').click();page.locator('#suppression').fill('100')
    check('helper changes setting without choosing target',page.evaluate('comparisonProbe.state.amount===1 && comparisonProbe.state.selection===null'))
    page.locator('#point-tools summary').click()
    index=page.evaluate('COMPARISON_DATA.cases[1].sources[1].findIndex(s=>s.x===59)+1')
    button=page.get_by_role('button',name=f'Выбрать точку {index}',exact=True)
    button.focus();page.keyboard.press('Enter')
    check('keyboard alternative selects same real point',page.evaluate('comparisonProbe.state.selection.point.x===59'))
    page.emulate_media(reduced_motion='no-preference');page.locator('#follow').click()
    check('check locks editing',page.locator('#suppression').is_disabled())
    page.emulate_media(reduced_motion='reduce');page.wait_for_function('comparisonProbe.state.phase==="result"')
    check('changing motion preference does not freeze check',page.evaluate('comparisonProbe.state.result.outcome==="moving"'))
    check('two field completion saved',page.locator('#journal-count').inner_text()=='2 / 2')
    snap('journal')
    check('next science chapter offered after two tracks',page.locator('#brightness-invitation').is_visible())
    tracking_snapshot=page.evaluate('JSON.stringify(comparisonProbe.state.attempts)')
    page.locator('#next-field').click()
    check('brightness chapter has a concrete goal',page.locator('#brightness-episode').is_visible() and page.locator('#tracking-episode').is_hidden() and page.locator('#brightness-measure').is_disabled())
    snap('brightness-entry')
    def brightness_point(x,y):
        canvas=page.locator('#brightness-first');canvas.scroll_into_view_if_needed();box=canvas.bounding_box()
        page.mouse.click(box['x']+(x+.5)/128*box['width'],box['y']+(y+.5)/128*box['height'])
    def brightness_measure(outcome):
        page.locator('#brightness-measure').click()
        page.wait_for_function('brightnessEpisode.state.phase==="result"')
        check('brightness measured outcome '+outcome,page.evaluate('brightnessEpisode.state.result.outcome')==outcome)
    brightness_point(80,80)
    check('brightness empty click leaves action unavailable',page.locator('#brightness-measure').is_disabled())
    brightness_point(23,64);brightness_measure('stable')
    check('stable selection cannot reveal supernova story',page.locator('#brightness-reveal').is_hidden() and not page.evaluate('brightnessEpisode.state.earned'))
    check('stable comparison uses raw flux and actual 2percent change',page.locator('#brightness-value-second').inner_text()=='98' and 'Общая' in page.locator('#brightness-chart-label').inner_text())
    snap('brightness-stable')
    previous=page.evaluate('JSON.stringify(brightnessEpisode.state.attempts[0])')
    page.locator('#brightness-retry').click();brightness_point(6,52);brightness_measure('unresolved')
    check('edge uncertainty not shown as a supernova',page.locator('#brightness-reveal').is_hidden() and page.locator('#brightness-chart').is_hidden())
    page.locator('#brightness-retry').click()
    page.locator('#brightness-help summary').click()
    raw_image=page.locator('#brightness-first').evaluate('(canvas)=>canvas.toDataURL()')
    page.locator('#brightness-difference').click()
    check('helper changes real rendered pixels',raw_image!=page.locator('#brightness-first').evaluate('(canvas)=>canvas.toDataURL()'))
    snap('brightness-difference')
    brightness_point(65,64)
    check('first frame click snaps to measured peak not catalog',page.evaluate('brightnessEpisode.state.selection.point.x===65 && brightnessEpisode.state.selection.point.y===64'))
    brightness_measure('faded')
    check('real fading shown as100to34',page.locator('#brightness-value-first').inner_text()=='100' and page.locator('#brightness-value-second').inner_text()=='34')
    check('previous scientific attempt is immutable and retained',previous==page.evaluate('JSON.stringify(brightnessEpisode.state.attempts[0])') and page.evaluate('Object.isFrozen(brightnessEpisode.state.attempts[0].result)'))
    check('historical story remains closed until requested',page.locator('#brightness-story').is_hidden() and page.locator('#brightness-reveal').is_visible())
    snap('brightness-result')
    saved_measurement=page.evaluate('JSON.stringify(brightnessEpisode.state.result)')
    page.locator('#brightness-difference').click()
    check('display helper does not rewrite photometry',saved_measurement==page.evaluate('JSON.stringify(brightnessEpisode.state.result)'))
    page.locator('#brightness-reveal').click()
    check('story names object and real ML roles',page.locator('#brightness-story').is_visible() and all(text in page.locator('#brightness-story').inner_text() for text in ['SN 2023tyk','BTSbot','SNIascore','спектр']))
    check('illustration and historic model separated from current measurement','Художественная иллюстрация' in page.locator('#brightness-story').inner_text() and 'не запускает' in page.locator('#brightness-story').inner_text())
    snap('brightness-story')
    page.set_viewport_size({'width':390,'height':844})
    check('brightness mobile no horizontal overflow',page.evaluate('document.documentElement.scrollWidth<=innerWidth'))
    page.locator('#brightness-return-observation').click();snap('brightness-mobile-result')
    page.locator('#brightness-retry').click()
    attempt_count=page.evaluate('brightnessEpisode.state.attempts.length')
    page.locator('#brightness-open-saved').click()
    check('journal reopens earned measurement without another attempt',page.locator('#brightness-value-second').inner_text()=='34' and attempt_count==page.evaluate('brightnessEpisode.state.attempts.length'))
    page.locator('#brightness-retry').click()
    page.locator('#brightness-tab-second').click()
    check('mobile compares one full sized exposure at a time',page.locator('#brightness-first-frame').is_hidden() and page.locator('#brightness-second-frame').is_visible())
    page.locator('#brightness-tab-first').click();brightness_point(65,64);brightness_measure('faded')
    check('raw mode also yields same measurement on mobile',page.locator('#brightness-value-second').inner_text()=='34' and not page.evaluate('brightnessEpisode.state.difference'))
    page.locator('#brightness-back').click()
    check('return preserves tracking attempts and brightness reward',tracking_snapshot==page.evaluate('JSON.stringify(comparisonProbe.state.attempts)') and page.evaluate('brightnessEpisode.state.earned'))
    page.set_viewport_size({'width':1440,'height':1050})
    page.locator('#start-brightness').click();page.locator('#brightness-retry').click()
    page.locator('#brightness-point-tools summary').click()
    source_index=page.evaluate('BRIGHTNESS_DATA.sources[0].findIndex(p=>p.x===65)+1')
    page.get_by_role('button',name=f'Проверить точку {source_index}',exact=True).focus();page.keyboard.press('Enter')
    check('brightness keyboard target choice works',page.evaluate('brightnessEpisode.state.selection.point.x===65'))
    page.emulate_media(reduced_motion='no-preference');page.locator('#brightness-measure').click()
    check('brightness measuring locks helper',page.locator('#brightness-difference').is_disabled())
    page.locator('#brightness-back').click();page.wait_for_timeout(800)
    check('leaving during measurement cancels pending attempt',page.evaluate('brightnessEpisode.state.phase==="search"'))
    page.emulate_media(reduced_motion='reduce')
    page.locator('#retry').click();point(59,65);follow('moving')
    check('replaying same field does not duplicate reward',page.evaluate('comparisonProbe.state.journal.length===2'))
    page.locator('#restart').click()
    check('restart clears brightness progress',page.evaluate('!brightnessEpisode.state.earned && brightnessEpisode.state.attempts.length===0'))
    check('restart clears progress and choice',page.evaluate('comparisonProbe.state.journal.length===0 && comparisonProbe.state.attempts.length===0 && comparisonProbe.state.selection===null'))
    page.locator('#card-tracking').click()
    page.set_viewport_size({'width':390,'height':844})
    page.wait_for_function('comparisonProbe.game.scale.width===480')
    snap('mobile-entry')
    check('phone has no horizontal overflow',page.evaluate('document.documentElement.scrollWidth<=innerWidth'))
    page.locator('#frame-first').click();check('phone can inspect first exposure',page.evaluate('comparisonProbe.state.mobileView===0'))
    page.locator('#frame-second').click();point(58,68)
    check('phone coordinate mapping selects target',page.evaluate('comparisonProbe.state.selection.point.x===58'))
    follow('moving');snap('mobile-result')
    check('phone result preserves progress',page.evaluate('comparisonProbe.state.journal.length===1'))
    page.set_viewport_size({'width':1365,'height':950})
    page.wait_for_function('comparisonProbe.game.scale.width===960')
    check('resize preserves result',page.evaluate('comparisonProbe.state.result.outcome==="moving"'))
    # Replay guards also prevent a stale scheduled check from writing into reset state.
    page.evaluate('comparisonProbe.reset();comparisonProbe.choose(58,68);comparisonProbe.follow();comparisonProbe.reset()')
    page.wait_for_timeout(1000)
    check('reset cancels pending verification',page.evaluate('comparisonProbe.state.phase==="search" && comparisonProbe.state.journal.length===0'))
    check('no runtime errors',not errors)
    browser.close()
report={'count':len(checks),'checks':checks,'engine':engine,'entry':ENTRY,'errors':errors}
(OUT/'browser.json').write_text(json.dumps(report,ensure_ascii=False,indent=2))
print(json.dumps(report,ensure_ascii=False,indent=2))
