*
!designlab/
!designlab/galaxy-shift/
!designlab/galaxy-shift/releases/
!designlab/galaxy-shift/releases/web/
!designlab/galaxy-shift/releases/web/**
!designlab/galaxy-shift/releases/galaxy-shift.zip
