*
!designlab/
!designlab/galaxy-shift/
!designlab/galaxy-shift/releases/
!designlab/galaxy-shift/releases/web/
!designlab/galaxy-shift/releases/web/**
!designlab/galaxy-shift/releases/galaxy-shift.zip

!designlab/comparison/
!designlab/comparison/docs/
!designlab/comparison/docs/**
!tools/
!tools/galaxy-release/
!tools/galaxy-release/nginx.conf
