/* Visible, guided CNN experiment. It explains a fixed, precomputed comparison;
   no filter diagram is claimed to be an activation from the calculated model. */
(function (root) {
  'use strict';
  function render(state) {
    const stage = state.cnnGuide || 'intro';
    if (stage === 'intro') return `<section class="cnn-guide"><p class="cnn-guide__eyebrow">ОПЫТ С ГОТОВОЙ CNN</p><h2>Меняем устройство модели, а не твои метки</h2><p><b>Свёрточная нейронная сеть (CNN)</b> обрабатывает изображения последовательностью шагов — слоёв. <b>Архитектура</b> задаёт типы и порядок этих слоёв.</p><p>Ты уже разметил <b>обучающую выборку</b> — снимки с метками классов. Обучение для этих меток рассчитано заранее. Сейчас проверим, как одно изменение <b>архитектуры</b> влияет на предсказания на той же проверочной выборке.</p><div class="cnn-guide__network"><b>Готовая сеть</b><span>Снимок → слои обработки → класс</span></div><button class="primary" data-action="guide-open">Понять опыт →</button></section>`;
    if (stage === 'goal') return `<section class="cnn-guide"><p class="cnn-guide__eyebrow">ЦЕЛЬ ОПЫТА</p><h2>Сначала найдём признак</h2><p><b>Слой</b> — часть сети, которая преобразует данные. <b>Признак</b> — различимая закономерность, например граница между светлым диском и тёмным небом или её направление. <b>Свёрточный слой</b> применяет обучаемые фильтры. <b>Свёртка</b> — вычисление: фильтр поэлементно умножается на маленький участок снимка, а произведения складываются в отклик. Архитектура — устройство сети: типы и порядок её слоёв.</p><details><summary>Как считает фильтр: учебный пример на 9 пикселях</summary><p>В этом примере 1 обозначает светлый пиксель, а 0 — тёмный. Числа фильтра задают, как учитывается каждый пиксель. При обучении сеть подбирает эти числа по примерам.</p><figure class="cnn-guide__diagram"><div><b>Участок</b><br><span class="cnn-guide__grid">1&nbsp; 0&nbsp; 1<br>0&nbsp; 1&nbsp; 0<br>1&nbsp; 0&nbsp; 1</span></div><span>×</span><div><b>Фильтр</b><br><span class="cnn-guide__grid">1&nbsp; 0&nbsp; 1<br>0&nbsp; 1&nbsp; 0<br>1&nbsp; 0&nbsp; 1</span></div><span>→</span><div><b>Отклик</b><br>1·1 + 0·0 + … = 5</div><figcaption>Учебная иллюстрация поэлементного умножения и суммы на участке 3 × 3; она не показывает активации этой готовой сети. На экране цепочка сокращена: остальные фиксированные шаги сети не изменяются.</figcaption></figure></details><p>Данные и метки не изменятся.</p><button class="primary" data-action="guide-next">Добавить один слой →</button></section>`;
    if (stage === 'change') return `<section class="cnn-guide"><p class="cnn-guide__eyebrow">ОДНО ИЗМЕНЕНИЕ</p><h2>Добавим вторую свёртку</h2><p>Первая свёртка ищет простые признаки. Вторая может соединять их в более сложный рисунок. Проверим, изменятся ли ответы. Дополнительный слой может помочь, но не гарантирует улучшения.</p><div class="cnn-guide__network"><b>Было</b><span>Снимок → свёртка → ReLU → класс</span><b>Станет</b><span>Снимок → свёртка → ReLU → свёртка → ReLU → класс</span></div><p>ReLU заменяет отрицательные значения нулями. Здесь она остаётся после каждого свёрточного слоя; остальные шаги сети закреплены и на этой короткой схеме не показаны.</p><button class="primary" data-action="guide-add-convolution">Добавить второй свёрточный слой</button></section>`;
    if (stage === 'compare') return `<section class="cnn-guide"><p class="cnn-guide__eyebrow">ПРОВЕРЯЕМ ТО ЖЕ</p><h2>Теперь проверим две свёртки</h2><p>Метки и проверочные снимки остались теми же. Откроем заранее рассчитанный результат для новой архитектуры и сравним конкретные предсказания.</p><button class="primary" data-action="run">Проверить модель →</button></section>`;
    if (stage === 'observe') return `<section class="cnn-guide"><p class="cnn-guide__eyebrow">СРАВНЕНИЕ</p><h2>Смотрим ответы до и после</h2><p>Метки и проверочные снимки не менялись. Сравни предсказания на трёх снимках выше. Какие ответы изменились? Правильных ответов могло стать больше, меньше или столько же: устройство сети само по себе не гарантирует улучшения.</p><button class="primary" data-action="guide-confirm-compare">Я сравнил ответы →</button></section>`;
    return '';
  }
  root.GalaxyCNNGuide = Object.freeze({ render });
})(globalThis);
